title:              DH의 블로그
email:              dhjung081121@gmail.com
description:        음악과 영상과 요리와 여행과 크로스핏을 사랑하는 공대생
author:             Jung Donghyuk
baseurl:            ""
url:                "https://jungdonghyuk.github.io"

# Social Profiles
twitter_username:  
github_username:    jungdonghyuk
facebook_username:  dhjung990120
instagram_username:  dhjung081121
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-1XM9EMX1XV # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
