title:              Clean Blog
email:              dhjung081121@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Jung Donghyuk
baseurl:            ""
url:                "https://jungdonghyuk.github.io"

# Social Profiles
twitter_username:  
github_username:    jungdonghyuk
facebook_username:  dhjung081121
instagram_username:  dhjung081121
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
